### ISSUE TITLE
Default -p option for CDQI tool

### ISSUE THREAD

**Issue by patgoley** [Prosumma/CoreDataQueryInterface#57]
If I run the tool without -p, I get compiler errors on my `Entity` conformance extensions. The errors state `typealias CDQIAttribute` must be public because it matches a requirement in protocol `Entity`. Works fine if I run with -p. Compiled using Xcode 8.3.2, Swift 3.1

**Comment by invoy-ghigley** [comment]
Yes, I've seen this problem myself. It only occurs when I use the auto-generated "invisible" model classes with Core Data. These classes seem to be `public` by default. Conversely, if you create a "visible" model class, this is `internal` by default, which means defaulting `-p` will give compiler warnings.

If we make `-p` default, we need to add a _new_ flag to turn it off. I sometimes want to create "visible" model classes because I override methods such as `awakeFromInsert`.

Thoughts?

**Comment by invoy-ghigley** [comment]
I have no problem with `public` being the default, by the way. I suspect that most people will use the auto-generated "invisible" model classes, so this is a sensible default.

Maybe we need something like this:

```sh
cdqi --visibility internal Model
cdqi -v public Model # This is the default
```

We would leave the `-p` flag as an alias for `--visibility public` for backwards compatibility reasons, however, making it the default effectively renders it a no-op.

Does this sound reasonable?

**Comment by Revolucent** [comment]
@patgoley By the way, if you like this proposal, would you mind submiting a pull request? :)

**Comment by Revolucent** [comment]
@patgoley If you like this proposal, please submit a pull request.

**Comment by patgoley** [comment]
@Revolucent Absolutely, just wanted to get your thoughts first. Will submit one soon. Thanks!

**Comment by Revolucent** [comment]
@patgoley As I said in #54, I want to create another project for the `cdqi` tool and make you the maintainer, assuming it's a responsibility you want to take on. Then we'd alter the main CDQI readme with instructions for installing it as a gem.
